### PR TITLE
New version. Works well with up to date owr with this https://github.com/EricssonResearch/openwebrtc/pull/124 PR landed.

### PR DESCRIPTION
**Pull request by stefhak**
I think I addressed P-E's comments.

### CODE REVIEW

**Comment by stefhak** [comment]
Updated the bridgeserver PR; number 127 PR should land for openwebrtc (though 124 would also work with this extension)

**Comment by stefhak** [comment]
The owr bridgeserver is now updated (the associated PR was landed yesterday), so this one could also be landed now, right?

**Comment by superdump** [comment]
If @adam-be and @pererikb confirm that this is ready to land, I will land it. :smile:

**Comment by stefanalund** [comment]
Did some more testing with the new extension:

* When using the compiled extension the door hanger shows up, but after clicking the Allow button the whole widget goes grey and video is not started
* If I compile it myself from the source files it works better. Clicking Allow works and the widget goes red as intended.
* Clicking the video camera icon does nothing in both scenarios.
* Camera icon is not Retina ready and looks broken.

**Comment by stefhak** [comment]
Thanks for testing.
I'll dig into why clicking the camera symbol does not make anything happen (for me it does always)
The actual icon was drawn as easily and quickly as I could - is there any tool available to create "Retina" ready icons?

**Comment by stefanalund** [comment]
You typically double the resolution (@2x). I just sent you some Retina-ready icons so that you don't have to use your drawing skills :)

**Comment by stefhak** [comment]
So, updated the version at stefhak/openwebrtc-browser-extensions, branch "reduced" to use new icon.
Clicking the icon always works for me. Note that it is disabled when there in no use of cam/mike, or no use being requested. Also, note that it is quite sluggish to respond to clicks, you need to click and give it a sec or so before releasing. I think that is inherit in the Toolbar, has nothing to do with my design.
BTW, the built version at stefhak/openwebrtc-browser-extensions, branch "reduced"  should also be OK.

**Comment by stefhak** [comment]
Updated (style things only) after review. PTAL.

**Pull request merged**
